"use client";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import type { Contract, Citation, Obligation } from "../lib/types";

const title = (text: string) => text.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
function Source({ citation }: { citation: Citation }) { return <button className="citation" title={citation.quote}>§ {citation.section_ref} · p. {citation.page}</button>; }

export default function Home() {
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [selected, setSelected] = useState<Contract | null>(null);
  const [tab, setTab] = useState<"terms" | "risks" | "obligations" | "ask">("terms");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { api.list().then(setContracts).catch(() => setError("Start the FastAPI backend to load contracts.")); }, []);
  const allRisks = useMemo(() => contracts.flatMap(c => c.risks), [contracts]);
  const allObligations = useMemo(() => contracts.flatMap(c => c.obligations), [contracts]);
  async function loadDemo() { setBusy(true); setError(""); try { const c = await api.demo(); setContracts(x => [...x, c]); setSelected(c); } catch (e) { setError(e instanceof Error ? e.message : "Could not load demo"); } finally { setBusy(false); } }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(""); try { const c = await api.upload(file); setContracts(x => [...x, c]); setSelected(c); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); } finally { setBusy(false); event.target.value = ""; } }
  async function markDone(item: Obligation) { if (!selected) return; const changed = await api.updateObligation(selected.id, item.id, "done"); setSelected({ ...selected, obligations: selected.obligations.map(x => x.id === changed.id ? changed : x) }); setContracts(xs => xs.map(c => c.id === selected.id ? { ...c, obligations: c.obligations.map(x => x.id === changed.id ? changed : x) } : c)); }
  if (selected) return <ContractView contract={selected} tab={tab} setTab={setTab} onBack={() => setSelected(null)} onDone={markDone} />;
  return <main><Header /><section className="hero"><div><p className="eyebrow">CONTRACT OPERATIONS</p><h1>Every promise, <em>proven.</em></h1><p className="lead">Turn static agreements into a cited, deadline-aware review workspace.</p></div><div className="actions"><button className="ghost" disabled={busy} onClick={loadDemo}>{busy ? "Analyzing…" : "Load demo contract"}</button><label className="primary">Upload contract<input type="file" accept=".pdf,.docx,.txt" onChange={upload} /></label></div></section>{error && <p className="error">{error}</p>}<section className="metrics"><Metric value={contracts.length} label="Active contracts" /><Metric value={allObligations.length} label="Tracked obligations" /><Metric value={allRisks.filter(r => r.severity === "high" && r.status === "open").length} label="Open high risks" /><Metric value={allRisks.filter(r => r.status === "open").length} label="Needs review" /></section><section className="dashboard"><article className="panel"><PanelTitle title="Contracts" detail="Cited review workspaces" /><div>{contracts.length ? contracts.map(c => <button key={c.id} className="contract-row" onClick={() => setSelected(c)}><span className="doc">§</span><span><strong>{c.title}</strong><small>{c.contract_type} · {c.clauses.length} clauses · Ready</small></span><span className="ready">Ready</span></button>) : <Empty text="Upload a contract or load the demo to begin." />}</div></article><article className="panel"><PanelTitle title="Review queue" detail="Human attention requested" /><div>{allRisks.length ? allRisks.slice(0, 4).map(r => <div className={`risk ${r.severity}`} key={r.id}><b>{r.severity} · {title(r.category)}</b><p>{r.explanation}</p><Source citation={r.citation} /></div>) : <Empty text="No review flags yet." />}</div></article><article className="panel"><PanelTitle title="Upcoming obligations" detail="Stay ahead of commitments" /><div>{allObligations.length ? allObligations.slice(0, 4).map(o => <div className="timeline" key={o.id}><time>{o.due_date ?? "OPEN"}</time><span><b>{o.description}</b><small>{title(o.obligation_type)} · {o.status}</small></span></div>) : <Empty text="No obligations detected yet." />}</div></article></section><p className="legal">ContractLens is an AI-assisted review tool, not a source of legal advice. Verify every result against its linked contract text.</p></main>;
}

function ContractView({ contract, tab, setTab, onBack, onDone }: { contract: Contract; tab: string; setTab: (tab: "terms" | "risks" | "obligations" | "ask") => void; onBack: () => void; onDone: (o: Obligation) => Promise<void> }) { return <main><Header /><button className="back" onClick={onBack}>← Dashboard</button><div className="contract-heading"><div><p className="eyebrow">{contract.contract_type} · READY FOR REVIEW</p><h1>{contract.title}</h1><p className="lead">{contract.clauses.length} parsed clauses · every result links to source</p></div><span className="ready">Processing complete</span></div><section className="workspace"><article className="panel document"><p className="viewer-label">SOURCE DOCUMENT</p>{contract.raw_text}</article><article className="panel side"><nav className="tabs">{(["terms", "risks", "obligations", "ask"] as const).map(item => <button key={item} onClick={() => setTab(item)} className={tab === item ? "active" : ""}>{title(item)}</button>)}</nav>{tab === "terms" && <Terms contract={contract} />}{tab === "risks" && <Risks contract={contract} />}{tab === "obligations" && <Obligations contract={contract} onDone={onDone} />}{tab === "ask" && <Ask contract={contract} />}</article></section><p className="legal">ContractLens does not provide legal advice. Confirm cited text with an authorized reviewer.</p></main> }
function Terms({ contract }: { contract: Contract }) { return <div><h2>Key terms</h2>{contract.extractions.map(e => <div className="term" key={e.field_name}><b>{title(e.field_name)}</b><p>{e.value}</p><span className="confidence">{Math.round(e.confidence * 100)}% confidence</span><Source citation={e.citation} /></div>)}</div> }
function Risks({ contract }: { contract: Contract }) { return <div><h2>Review flags</h2>{contract.risks.map(r => <div className={`risk ${r.severity}`} key={r.id}><b>{r.severity} · {title(r.category)}</b><p>{r.explanation}</p><small>Recommended: {r.recommendation}</small><Source citation={r.citation} /></div>)}</div> }
function Obligations({ contract, onDone }: { contract: Contract; onDone: (o: Obligation) => Promise<void> }) { return <div><h2>Obligation timeline</h2>{contract.obligations.map(o => <div className="term" key={o.id}><b>{title(o.obligation_type)} · {o.status}</b><p>{o.description}</p><small>{o.responsible_party} · {o.due_rule ?? "No fixed date"}</small><Source citation={o.citation} />{o.status !== "done" && <button className="done" onClick={() => onDone(o)}>Mark done</button>}</div>)}</div> }
function Ask({ contract }: { contract: Contract }) { const [question, setQuestion] = useState(""); const [response, setResponse] = useState<{ answer: string; citations: { section_ref: string }[]; confidence: number } | null>(null); const [busy, setBusy] = useState(false); async function submit() { if (!question) return; setBusy(true); try { setResponse(await api.ask(contract.id, question)); } finally { setBusy(false); } } return <div><h2>Ask this contract</h2><p className="muted">Answers are limited to retrieved clauses and refuse unsupported claims.</p><div className="ask"><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Can we terminate early?" /><button className="primary" onClick={submit}>{busy ? "Searching…" : "Ask"}</button></div>{response && <div className="answer"><p>{response.answer}</p><small>{response.citations.map(c => `§ ${c.section_ref}`).join(", ") || "No supporting clause"} · {Math.round(response.confidence * 100)}% confidence</small></div>}</div> }
function Header() { return <header><a className="brand" href="/">Contract<span>Lens</span></a><nav><span>Dashboard</span><span>Contracts</span><span>Obligations</span><span>Review queue</span></nav><small>AI-assisted review · not legal advice</small></header> }
function Metric({ value, label }: { value: number; label: string }) { return <article className="metric"><b>{value}</b><span>{label}</span></article> }
function PanelTitle({ title, detail }: { title: string; detail: string }) { return <div className="panel-title"><h2>{title}</h2><small>{detail}</small></div> }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div> }
